### PR TITLE
Fixes To Quick charge

### PR DESCRIPTION
**Pull request by Yrahate7**
The HVDCP_OPTI daemon is responsible for quick charge activation.
Activate it in the Off mode charge too,this will allow for 9 volt regulation request.

### CODE REVIEW

**Comment by mdeejay** [comment]
Nope. Not working on oreo. Breaks QC

**Comment by Yrahate7** [comment]
Okay, There's another way to activate it. I have a kernel module to look after it.
I'll test it and then upload.
Unfortunately my device is still bootloader locked. Have to wait 15 days
😑

**Comment by mdeejay** [comment]
QC works without this binary. support 9V

**Comment by Yrahate7** [comment]
Okay.

**Pull request closed without merging**
